### ISSUE TITLE
Create latest version's repo?

### ISSUE THREAD

**Issue by f3rnando** [crypti/whitepaper#3]
I just wanted to fork and branch an _es_ES_ translation of this white paper but noticed that its an older version. 
How do you suggest to start translating in a versioned way?
Thanks.

**Comment by borispovod** [comment]
@f3rnando hi, we don't have latest version in repository, i need to ask @MaxKK what we going to do with it

**Comment by maxkordek** [comment]
https://crypti.me/crypti.pdf

This link provides the latest version. Right now everything is done though Word, but I think it might be wise to transcript the white paper to markdown. This way we can make different versions. 

@f3rnando @crypti what do you guys think? If you agree I will prepare it in the next few days.

**Comment by f3rnando** [comment]
https://github.com/f3rnando/crypti-whitepaper.md
Spanish translation, WIP: https://github.com/f3rnando/crypti-whitepaper.md/blob/master/crypti-whitepaper-es.md
@MaxKK, I can transfer the repo to @crypti

**Comment by borispovod** [comment]
@f3rnando nice

i merged it to this repo https://github.com/crypti/whitepaper/blob/master/es.md
